spring:
  application:
    name: springboot_fm_example

rox:
  key: 4428b893-9511-47eb-7c05-a95f62ba4e23

  options:
    getConfigApiEndpoint: "https://api.cloudbees.io/device/get_configuration"
    getConfigCloudEndpoint: "https://rox-conf.cloudbees.io/"
    sendStateApiEndpoint: "https://api.cloudbees.io/device/update_state_store/"
    sendStateCloudEndpoint: "https://rox-state.cloudbees.io/"
    analyticsEndpoint: "https://fm-analytics-preprod.saas-preprod.beescloud.com"
    pushNotificationsEndpoint: "https://sdk-notification-service.cloudbees.io/sse"
    retry:
      maxAttempts: 5  # Retry logic in case of connection failure
      backoff:
        delay: 5000  # 5-second delay between retries

logging:
  level:
    root: DEBUG
    io.rollout: DEBUG  # Enabling DEBUG logs for the io.rollout package
