apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Naveen workflow

on:
  push:
    branches:
      - Naveen

jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Gradle Wrapper
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          ./gradlew wrapper # Ensure the wrapper files are generated

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          chmod +x gradlew # Ensure the Gradle wrapper is executable
          ./gradlew clean build bootRun # Execute with Gradle wrapper
